### ISSUE TITLE
Shared razor class library for common Blazor components

### ISSUE THREAD

**Issue by BlockchainPunks** [syncfusion/blazor-showcase-diagram-builder#23]
Your example duplicates the razor pages in each example: maui, server and wasm 

Telerik team have an example where a common razor class li tart exists to avoid such duplication- can you update your example like this as it’s painful having to update in 3 places for common change

**Comment by Keerthivasan-Ramamoorthy** [comment]
The common razor class library has been shared across Blazor Server, WASM, and MAUI Diagram Builder projects
